version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "xxxx:xxxx"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "xxxx:xxxx"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: xxxxxxxxxx
      KAFKA_ADVERTISED_PORT: xxxx
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_ZOOKEEPER_PORT: xxxx
    depends_on:
      - zookeeper
